In [24]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [3]:
loaded_model = tf.keras.models.load_model('./saved')

In [66]:
img = keras.preprocessing.image.load_img(
    'Test/20210515_224626.jpg', target_size=(216, 216)
)

In [67]:
img.show()

In [68]:
img_arr = keras.preprocessing.image.img_to_array(img)

In [69]:
img_arr = tf.expand_dims(img_arr, 0)

In [70]:
print(img_arr)

tf.Tensor(
[[[[187. 163. 117.]
   [181. 157. 109.]
   [182. 155. 108.]
   ...
   [191. 171. 134.]
   [190. 170. 137.]
   [189. 169. 144.]]

  [[184. 160. 116.]
   [183. 159. 115.]
   [187. 163. 117.]
   ...
   [192. 170. 133.]
   [194. 171. 137.]
   [186. 163. 129.]]

  [[182. 157. 117.]
   [183. 159. 115.]
   [182. 158. 114.]
   ...
   [191. 168. 134.]
   [191. 168. 134.]
   [189. 166. 132.]]

  ...

  [[199. 179. 142.]
   [203. 183. 146.]
   [205. 185. 148.]
   ...
   [205. 185. 150.]
   [206. 186. 151.]
   [203. 183. 148.]]

  [[197. 177. 140.]
   [202. 182. 145.]
   [199. 179. 142.]
   ...
   [206. 186. 151.]
   [204. 184. 149.]
   [201. 181. 144.]]

  [[202. 182. 145.]
   [209. 189. 152.]
   [201. 181. 144.]
   ...
   [203. 183. 148.]
   [199. 179. 144.]
   [205. 185. 150.]]]], shape=(1, 216, 216, 3), dtype=float32)


In [71]:
predictions = loaded_model.predict(img_arr)

In [72]:
print(predictions)

[[4.0696664 8.649735 ]]


In [73]:
class_names = ['Brachiosaurus', 'Trex']
score = tf.nn.softmax(predictions[0])
print("This is a {} with a {:.2f} percent confidence".format(class_names[np.argmax(score)], 100*np.max(score)))

This is a Trex with a 98.98 percent confidence
