In [24]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [3]:
loaded_model = tf.keras.models.load_model('./saved')

In [34]:
img = keras.preprocessing.image.load_img(
    'Test/20210515_195922.jpg', target_size=(216, 216)
)

In [35]:
img.show()

In [36]:
img_arr = keras.preprocessing.image.img_to_array(img)

In [37]:
img_arr = tf.expand_dims(img_arr, 0)

In [38]:
print(img_arr)

tf.Tensor(
[[[[ 67.  49.   3.]
   [ 84.  63.  16.]
   [ 79.  55.  11.]
   ...
   [251. 243. 222.]
   [251. 243. 222.]
   [254. 246. 225.]]

  [[ 77.  49.   9.]
   [ 82.  54.  15.]
   [ 74.  46.   7.]
   ...
   [253. 245. 224.]
   [252. 244. 223.]
   [254. 246. 225.]]

  [[ 36.  11.   0.]
   [ 59.  33.   0.]
   [ 66.  37.   5.]
   ...
   [254. 246. 225.]
   [251. 243. 222.]
   [250. 242. 221.]]

  ...

  [[151. 118.  73.]
   [151. 118.  73.]
   [149. 116.  73.]
   ...
   [219. 202. 159.]
   [213. 196. 152.]
   [215. 198. 154.]]

  [[151. 118.  75.]
   [154. 121.  78.]
   [150. 117.  74.]
   ...
   [218. 201. 158.]
   [217. 200. 157.]
   [218. 203. 160.]]

  [[153. 120.  75.]
   [152. 119.  76.]
   [151. 118.  75.]
   ...
   [219. 202. 159.]
   [219. 202. 159.]
   [220. 203. 160.]]]], shape=(1, 216, 216, 3), dtype=float32)


In [39]:
predictions = loaded_model.predict(img_arr)

In [40]:
print(predictions)

[[6.956646  6.1796207]]


In [41]:
class_names = ['Brachiosaurus', 'Trex']
score = tf.nn.softmax(predictions[0])
print("This is a {} with a {:.2f} percent confidence".format(class_names[np.argmax(score)], 100*np.max(score)))

This is a Brachiosaurus with a 68.50 percent confidence
